version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ruleta2324
      POSTGRES_DB: juegueygana_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  auth-service:
    build: ./backend/auth-service
    ports:
      - "8081:8081"
    environment:
      DATABASE_URL: jdbc:postgresql://postgres:5432/juegueygana_db
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - postgres

  app-service:
    build: ./backend/app-service
    ports:
      - "8082:8082"
    environment:
      DATABASE_URL: jdbc:postgresql://postgres:5432/juegueygana_db
    depends_on:
      - postgres

volumes:
  postgres_data:
